version: '3.8'

services:
  pg-backend:
    container_name: pg-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3030:80
    environment:
      - NODE_ENV=production
    env_file:
      - .env
